logging:
    level:
        com:
            zaxxer:
                hikari: TRACE
                hikari.HikariConfig: DEBUG
spring:
    cloud:
      gcp:
          sql:
              instance-connection-name: xcode-ingot:us-central1:xcode-hinalang
              database-name: hinalang
    datasource:
        hikari:
            maximum-pool-size: 10
        username: ENC(Te/HiLESkKgrvPIThZ3Yzg==)
        password: ENC(Fr8Wmmyf73fWa0OzrzUeveh4oM0UczsKtAYs3qi4AO0=)
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ENC(+Mdm65zhWMuOuBk0Sxt3TgNNNwGz8JOnPizAySeKyzA=)
        password: ENC(8AiqB0T5+yGIivxnjhunBxqWz6YYe8lv1C0TRM2Zn40=)
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        test-connection: false
        default-encoding: utf-8
jasypt:
    encryptor:
        password: xcode
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator